<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\solvace.timeline.domain\solvace.timeline.domain.csproj" />
      <ProjectReference Include="..\..\..\Cime.BuildingBlocks\src\Cime.BuildingBlocks.RealTime\Cime.BuildingBlocks.RealTime.csproj" />
    </ItemGroup>

</Project>
