<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" /> 
        <ProjectReference Include="..\..\..\Cime.BuildingBlocks\src\Cime.BuildingBlocks.GlobalModels\Cime.BuildingBlocks.GlobalModels.csproj" /> 
        <ProjectReference Include="..\..\..\Solvace.PullRequests\src\solvace.prform.application\solvace.prform.application.csproj" /> 
        <ProjectReference Include="..\solvace.azure.domain\solvace.azure.domain.csproj" />
        <ProjectReference Include="..\solvace.azure.infra\solvace.azure.infra.csproj" />
    </ItemGroup>

</Project>


