// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using solvace.vacations.infra.Contexts;

#nullable disable

namespace solvace.vacations.infra.Migrations
{
    [DbContext(typeof(VacationContext))]
    partial class VacationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vacations")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("solvace.vacations.domain.Entities.UserVacationBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquisitionPeriodEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("AcquisitionPeriodStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("AvailableDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UsagePeriodEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UsagePeriodStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsedDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AcquisitionPeriodStart", "AcquisitionPeriodEnd")
                        .IsUnique();

                    b.HasIndex("UserId", "UsagePeriodStart", "UsagePeriodEnd");

                    b.ToTable("UserVacationBalances", "vacations");
                });

            modelBuilder.Entity("solvace.vacations.domain.Entities.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedByManagerAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ApprovedByManagerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AuthorizedByHRAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AuthorizedByHRId")
                        .HasColumnType("uuid");

                    b.Property<int>("BusinessDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HRNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("VacationRequests", "vacations");
                });
#pragma warning restore 612, 618
        }
    }
}
