// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using solvace.executionplans.infra.Contexts;

#nullable disable

namespace solvace.executionplans.infra.Migrations
{
    [DbContext(typeof(ExecutionPlanContext))]
    [Migration("20261006211133_PullRequestChecks")]
    partial class PullRequestChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("execution")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StepKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("PlanId", "Kind", "Name")
                        .IsUnique();

                    b.ToTable("ExecutionArtifacts", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionArtifactContent", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ArtifactId");

                    b.ToTable("ExecutionArtifactContents", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BlocksStep")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ChecksChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChecksFailed")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ChecksHeadSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChecksStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Repository")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TargetBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "StepKey");

                    b.ToTable("ExecutionLinks", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "ClientId")
                        .IsUnique();

                    b.HasIndex("PlanId", "Id");

                    b.ToTable("ExecutionLogs", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("FromExecutor")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("CardNumber", "Number");

                    b.ToTable("ExecutionNotes", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NotesReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NotesReadNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("analysis");

                    b.Property<DateTimeOffset?>("ResumeHandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResumeRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResumeRequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ParentPlanId");

                    b.HasIndex("CardNumber", "CreatedAt");

                    b.ToTable("ExecutionPlans", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowFreeText")
                        .HasColumnType("boolean");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnsweredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AnsweredVia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StepKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Status");

                    b.ToTable("ExecutionQuestions", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentActivity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("CurrentActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentActivityTool")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FinishedReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("Force")
                        .HasColumnType("boolean");

                    b.Property<long?>("FreshInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NewSession")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phase")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Pid")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecentActivities")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SessionCostUsd")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("SessionCwd")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionHost")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StderrTail")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetWorkerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Turns")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WaitReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ExecutionRequests_ActiveCard")
                        .HasFilter("\"Status\" IN ('queued', 'claimed', 'running')");

                    b.HasIndex("CardNumber", "CreatedAt");

                    b.HasIndex("OwnerUserId", "Status");

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("ExecutionRequests", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Checkpoint")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("DependsOn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("claude");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("task");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Repository")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaitingOn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Key")
                        .IsUnique();

                    b.ToTable("ExecutionSteps", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionUserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoAnalyzeEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("AutoAreaPaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("AutoAssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AutoLastCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AutoLastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("AutoMaxPerDay")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("AutoStates")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AutoWorkItemTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("DailyBudgetUsd")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("ExecutionUserSettings", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Capabilities")
                        .HasColumnType("jsonb");

                    b.Property<string>("ClaudeVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Doctor")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DoctorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DoctorRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Os")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SkillsVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ThrottledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Workspace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Host");

                    b.ToTable("ExecutionWorkers", "execution");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionArtifact", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionArtifactContent", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionArtifact", null)
                        .WithOne("Content")
                        .HasForeignKey("solvace.executionplans.domain.Entities.ExecutionArtifactContent", "ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionLink", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionLog", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionNote", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionPlan", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("ParentPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("solvace.executionplans.domain.Entities.ExecutionSession", "Sessions", b1 =>
                        {
                            b1.Property<Guid>("ExecutionPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("BaseCacheReadTokens");

                            b1.Property<long>("BaseCacheWriteTokens");

                            b1.Property<long>("BaseInputTokens");

                            b1.Property<int>("BaseKbCalls");

                            b1.Property<int>("BaseMcpCalls");

                            b1.Property<long>("BaseOutputTokens");

                            b1.Property<int>("BaseScriptCalls");

                            b1.Property<int>("BaseSearchCalls");

                            b1.Property<int>("BaseTurns");

                            b1.Property<bool>("BaselineSet");

                            b1.Property<long>("CacheReadTokens");

                            b1.Property<long>("CacheWriteTokens");

                            b1.Property<string>("Cwd")
                                .HasMaxLength(500);

                            b1.Property<string>("Host")
                                .HasMaxLength(200);

                            b1.Property<long>("InputTokens");

                            b1.Property<int?>("KbCalls");

                            b1.Property<DateTimeOffset>("LastSeenAt");

                            b1.Property<int?>("McpCalls");

                            b1.Property<string>("Model");

                            b1.Property<long>("OutputTokens");

                            b1.Property<int?>("ScriptCalls");

                            b1.Property<int?>("SearchCalls");

                            b1.Property<string>("SessionId")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<DateTimeOffset>("StartedAt");

                            b1.Property<int>("Turns");

                            b1.Property<DateTimeOffset?>("UsageUpdatedAt");

                            b1.HasKey("ExecutionPlanId", "__synthesizedOrdinal");

                            b1.ToTable("ExecutionPlans", "execution");

                            b1
                                .ToJson("Sessions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionPlanId");

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionExploredFile", "BaseExploredFiles", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Path")
                                        .IsRequired()
                                        .HasMaxLength(200);

                                    b2.Property<int>("Reads");

                                    b2.Property<long>("Tokens");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionModelUsage", "BaseModels", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("CacheReadTokens");

                                    b2.Property<long>("CacheWriteTokens");

                                    b2.Property<long>("InputTokens");

                                    b2.Property<string>("Model")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.Property<long>("OutputTokens");

                                    b2.Property<int>("Turns");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionReadSource", "BaseSources", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Calls");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasMaxLength(20);

                                    b2.Property<long>("Tokens");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionExploredFile", "ExploredFiles", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Path")
                                        .IsRequired()
                                        .HasMaxLength(200);

                                    b2.Property<int>("Reads");

                                    b2.Property<long>("Tokens");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionModelUsage", "Models", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("CacheReadTokens");

                                    b2.Property<long>("CacheWriteTokens");

                                    b2.Property<long>("InputTokens");

                                    b2.Property<string>("Model")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.Property<long>("OutputTokens");

                                    b2.Property<int>("Turns");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.OwnsMany("solvace.executionplans.domain.Entities.ExecutionReadSource", "Sources", b2 =>
                                {
                                    b2.Property<Guid>("ExecutionSessionExecutionPlanId");

                                    b2.Property<int>("ExecutionSession__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Calls");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasMaxLength(20);

                                    b2.Property<long>("Tokens");

                                    b2.HasKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ExecutionPlans", "execution");

                                    b2.WithOwner()
                                        .HasForeignKey("ExecutionSessionExecutionPlanId", "ExecutionSession__synthesizedOrdinal");
                                });

                            b1.Navigation("BaseExploredFiles");

                            b1.Navigation("BaseModels");

                            b1.Navigation("BaseSources");

                            b1.Navigation("ExploredFiles");

                            b1.Navigation("Models");

                            b1.Navigation("Sources");
                        });

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionQuestion", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("solvace.executionplans.domain.Requests.ExecutionQuestionOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("ExecutionQuestionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description");

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<bool>("Recommended");

                            b1.HasKey("ExecutionQuestionId", "__synthesizedOrdinal");

                            b1.ToTable("ExecutionQuestions", "execution");

                            b1
                                .ToJson("Options")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionQuestionId");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionStep", b =>
                {
                    b.HasOne("solvace.executionplans.domain.Entities.ExecutionPlan", null)
                        .WithMany("Steps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionArtifact", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("solvace.executionplans.domain.Entities.ExecutionPlan", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
